<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    exclude-result-prefixes="xs"
    version="3.0">
    
    <xsl:output method="xml" encoding="UTF-8"/>
    
    <xsl:template match="*|@*|text()">
        <xsl:copy>
            <xsl:apply-templates select="*|@*|text()"/>
        </xsl:copy>
    </xsl:template>
    
    <xsl:template match="article[//article-meta/article-version='1.1']//ref[mixed-citation[@publication-type='journal' and not(article-title)]]">
        <xsl:choose>
            <xsl:when test="@id='c4'">
                <ref id="c4"><mixed-citation publication-type="journal"><string-name><surname>Bolton</surname> <given-names>AD</given-names></string-name>, <string-name><surname>Murata</surname> <given-names>Y</given-names></string-name>, <string-name><surname>Kirchner</surname> <given-names>R</given-names></string-name>, <string-name><surname>Kim</surname> <given-names>S-Y</given-names></string-name>, <string-name><surname>Young</surname> <given-names>A</given-names></string-name>, <string-name><surname>Dang</surname> <given-names>T</given-names></string-name>, <string-name><surname>Yanagawa</surname> <given-names>Y</given-names></string-name>, <string-name><surname>Constantine-Paton</surname> <given-names>M</given-names></string-name>. <year>2015</year>. <article-title>A Diencephalic Dopamine Source Provides Input to the Superior Colliculus, where D1 and D2 Receptors Segregate to Distinct Functional Zones</article-title>. <source>Cell Rep</source> <volume>13</volume>:<elocation-id>1003&#x2013;1015</elocation-id>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c12'">
                <ref id="c12"><mixed-citation publication-type="journal"><string-name><surname>Chen</surname> <given-names>F</given-names></string-name>, <string-name><surname>Qian</surname> <given-names>J</given-names></string-name>, <string-name><surname>Cao</surname> <given-names>Z</given-names></string-name>, <string-name><surname>Li</surname> <given-names>A</given-names></string-name>, <string-name><surname>Cui</surname> <given-names>J</given-names></string-name>, <string-name><surname>Shi</surname> <given-names>L</given-names></string-name>, <string-name><surname>Xie</surname> <given-names>J.</given-names></string-name> <year>2023</year>. <article-title>Chemogenetic and optogenetic stimulation of zona incerta GABAergic neurons ameliorates motor impairment in Parkinson&#x2019;s disease</article-title>. <source>iScience</source> <volume>26</volume>:<elocation-id>107149</elocation-id>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c14'">
                <ref id="c14"><mixed-citation publication-type="book"><string-name><surname>Cohen</surname> <given-names>J.</given-names></string-name> <year>1988</year>. <source>Statistical power analysis for the behavioral sciences</source> <publisher-loc>New York</publisher-loc>. <publisher-name>NY: Academic</publisher-name> <fpage>54</fpage>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c36'">
                <ref id="c36"><mixed-citation publication-type="journal"><string-name><surname>Kim</surname> <given-names>L</given-names></string-name>, <string-name><surname>Chomiak</surname> <given-names>T</given-names></string-name>, <string-name><surname>Tran</surname> <given-names>MA</given-names></string-name>, <string-name><surname>Tam</surname> <given-names>S</given-names></string-name>, <string-name><surname>McPherson</surname> <given-names>C</given-names></string-name>, <string-name><surname>Eaton</surname> <given-names>SEA</given-names></string-name>, <string-name><surname>Ou</surname> <given-names>Y</given-names></string-name>, <string-name><surname>Kiss</surname> <given-names>ZHT</given-names></string-name>, <string-name><surname>Whelan</surname> <given-names>PJ.</given-names></string-name> <year>2021</year>. <article-title>Global remodelling of afferent and efferent projections of the A13 region following unilateral nigrostriatal degeneration using 6-hydroxydopamineNeuroscience Meeting Planner</article-title>. <source>Presented at the Society for Neuroscience</source>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c37'">
                <ref id="c37"><mixed-citation publication-type="journal"><string-name><surname>Kim</surname> <given-names>LH</given-names></string-name>, <string-name><surname>Chomiak</surname> <given-names>T</given-names></string-name>, <string-name><surname>Tran</surname> <given-names>M</given-names></string-name>, <string-name><surname>Tam</surname> <given-names>S</given-names></string-name>, <string-name><surname>McPherson</surname> <given-names>C</given-names></string-name>, <string-name><surname>Eaton</surname> <given-names>SEA</given-names></string-name>, <string-name><surname>Ou</surname> <given-names>Y</given-names></string-name>, <string-name><surname>Resch</surname> <given-names>L</given-names></string-name>, <string-name><surname>Kiss</surname> <given-names>ZHT</given-names></string-name>, <string-name><surname>Whelan</surname> <given-names>PJ.</given-names></string-name> <year>2021</year>. <article-title>Substantia nigra degradation results in widespread changes in medial zona incerta afferent and efferent connectomics</article-title>. <source>bioRxiv</source>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c41'">
                <ref id="c41"><mixed-citation publication-type="journal"><string-name><surname>Konnova</surname> <given-names>EA</given-names></string-name>, <string-name><given-names>Translational Neurogenetics</given-names> <surname>Unit</surname></string-name>, <string-name><given-names>Wallenberg Neuroscience</given-names> <surname>Center</surname></string-name>, <string-name><surname>Lund University</surname>, <given-names>Lund</given-names></string-name>, <string-name><surname>Sweden</surname>, <given-names>Swanberg M</given-names></string-name>, <string-name><given-names>Translational Neurogenetics</given-names> <surname>Unit</surname></string-name>, <string-name><given-names>Wallenberg Neuroscience</given-names> <surname>Center</surname></string-name>, <string-name><surname>Lund University</surname>, <given-names>Lund</given-names></string-name>, Sweden. <year>2018</year>. <article-title>Animal models of Parkinson&#x2019;s diseaseParkinson&#x2019;s Disease: Pathogenesis and Clinical Aspects</article-title>. <source>Codon Publications</source>. pp. <fpage>83</fpage>&#x2013;<lpage>106</lpage>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c47'">
                <ref id="c47"><mixed-citation publication-type="journal"><string-name><surname>Li</surname> <given-names>S</given-names></string-name>, <string-name><surname>Shi</surname> <given-names>Y</given-names></string-name>, <string-name><surname>Kirouac</surname> <given-names>GJ</given-names></string-name>. <year>2014</year>. <article-title>The hypothalamus and periaqueductal gray are the sources of dopamine fibers in the paraventricular nucleus of the thalamus in the rat</article-title>. <source>Front. Neuroanat</source> <volume>8</volume>:<elocation-id>136</elocation-id>. <pub-id pub-id-type="doi">10.3389/fnana.2014.00136</pub-id></mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c92'">
                <ref id="c92"><mixed-citation publication-type="journal"><string-name><surname>Sita</surname> <given-names>LV</given-names></string-name>, <string-name><surname>Elias</surname> <given-names>CF</given-names></string-name>, <string-name><surname>Bittencourt</surname> <given-names>JC</given-names></string-name>. <year>2007</year>. <article-title>Connectivity pattern suggests that incerto-hypothalamic area belongs to the medial hypothalamic system</article-title>. <source>Neuroscience</source> <volume>148</volume>:<fpage>949</fpage>&#x2013;<lpage>969</lpage>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c93a'">
                <ref id="c93a"><mixed-citation publication-type="journal"><string-name><surname>Stefani</surname> <given-names>A</given-names></string-name>, <string-name><surname>Lozano</surname> <given-names>AM</given-names></string-name>, <string-name><surname>Peppe</surname> <given-names>A</given-names></string-name>, <string-name><surname>Stanzione</surname> <given-names>P</given-names></string-name>, <string-name><surname>Galati</surname> <given-names>S</given-names></string-name>, <string-name><surname>Tropepi</surname> <given-names>D</given-names></string-name>, <string-name><surname>Pierantozzi</surname> <given-names>M</given-names></string-name>, <string-name><surname>Brusa</surname> <given-names>L</given-names></string-name>, <string-name><surname>Scarnati</surname> <given-names>E</given-names></string-name>, <string-name><surname>Mazzone</surname> <given-names>P</given-names></string-name>. <year>2007</year>. <article-title>Bilateral deep brain stimulation of the pedunculopontine and subthalamic nuclei in severe Parkinson&#x2019;s disease</article-title>. <source>Brain</source> <volume>130</volume>:<elocation-id>1596&#x2013;1607</elocation-id>.</mixed-citation></ref>
            </xsl:when>
            <xsl:when test="@id='c97'">
                <ref id="c97"><mixed-citation publication-type="journal"><string-name><surname>Tsang</surname> <given-names>E</given-names></string-name>, <string-name><surname>Orlandini</surname> <given-names>C</given-names></string-name>, <string-name><surname>Sureka</surname> <given-names>R</given-names></string-name>, <string-name><surname>Crevenna</surname> <given-names>AH</given-names></string-name>, <string-name><surname>Perlas</surname> <given-names>E</given-names></string-name>, <string-name><surname>Prankerd</surname> <given-names>I</given-names></string-name>, <string-name><surname>Masferrer</surname> <given-names>ME</given-names></string-name>, <string-name><surname>Gross</surname> <given-names>CT.</given-names></string-name> <year>2021</year>. <article-title>Induction of flight via midbrain projections to the cuneiform nucleus</article-title>. <source>bioRxiv</source>. doi:<pub-id pub-id-type="doi">10.1101/2021.12.21.473683</pub-id></mixed-citation></ref>
            </xsl:when>
        </xsl:choose>
    </xsl:template>
    
</xsl:stylesheet>