name: Verify XSLT transforms
on: push

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify output
        run: ./smoke_tests.sh
  project-tests:
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./project_tests.sh --log-file ./project-tests.log

      - name: Run tests in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt-test -f Dockerfile.test .
          docker run --rm epp-biorxiv-xslt-test /app/project_tests.sh --log-file /app/project-tests.log
