name: Verify XSLT transforms
on: push

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify output
        run: ./smoke_tests.sh
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./project_tests.sh --log ./project-tests.log

      - name: Run tests in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt-test -f Dockerfile.test .
          docker run --rm epp-biorxiv-xslt-test /app/project_tests.sh --log /app/project-tests.log
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ./scripts/transform.sh
        run: cat ./test/fixtures/kitchen-sink.xml | ./scripts/transform.sh
  process-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ./scripts/process-folder.sh
        run: ./scripts/process-folder.sh ./test/fixtures ./process-folder-dest
