name: Verify XSLT transform
on: push

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify output
        run: ./smoke_tests.sh
  project-tests:
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./project_tests.sh
