name: Verify XSLT transforms
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'


jobs:
  documentation-check:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for entry for each XSL in documentation
        run: ./scripts/verify-documentation.sh
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Run tests
        run: ./project_tests.sh --log ./project-tests.log

      - name: Run tests in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt-test -f Dockerfile.test .
          docker run --rm epp-biorxiv-xslt-test /app/project_tests.sh

      - name: Output project-tests.log
        run: cat ./project-tests.log

      - name: Preserve project-tests.log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./project-tests.log
  build-and-push:
    needs: [project-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/elifeciences/enhanced-preprints-biorxiv-xslt
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
