name: Verify XSLT transforms
on: push

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify output
        run: ./smoke_tests.sh
  project-tests:
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./project_tests.sh

      - name: Run tests in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt .
          docker run --rm -v "project_tests.sh:/app/project_tests.sh" -v "test:/app/test" epp-biorxiv-xslt /app/project_tests.sh
