name: Verify XSLT transforms
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  documentation-check:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for entry for each XSL in documentation
        run: ./scripts/verify-documentation.sh
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt:test --target test .
          docker run --rm epp-biorxiv-xslt:test
  build-and-push:
    needs: [project-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date --utc +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "commit_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-push
        with:
          push: true
          load: false
          platforms: linux/amd64,linux/arm64
          target: prod
          tags: |
            ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt:latest
            ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt:${{ github.sha }}
            ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt:master-${{ steps.commit_sha.outputs.commit_sha }}-${{ steps.date.outputs.date }}
      - name: Generate artefact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt
          subject-digest: ${{ steps.build-push.outputs.digest }}
