name: Verify API
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  check-api-build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node dependencies
        run: yarn

      - name: Run jest tests
        run: yarn test

      - name: Run api in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt:api --target api .
          docker run -d --name api-container -p 3000:80 epp-biorxiv-xslt:api

      - name: Verify that api is healthy
        run: |
          reps=60; s=5; i=0
          while [ "$(docker inspect --format='{{.State.Health.Status}}' api-container)" != "healthy" ]; do
            if [ $i -ge $reps ]; then
              echo "API is not healthy after $(($reps * $s)) seconds"
              exit 1
            fi
            echo "Waiting for API to become healthy $(($i * $s))s"
            sleep $s
            i=$((i+1))
          done
          echo "API is healthy"

      - name: Check api (passthrough)
        run: |
          output=$(curl --location 'http://localhost:3000' -H 'X-Passthrough: true' --data '<root><child>content</child></root>')
          expected_output='{"xml":"<root><child>content</child></root>","logs":["Passthrough mode!"]}';
          if [ "$output" != "$expected_output" ]; then
            exit 1
          fi
          echo "$output" | jq

      - name: Check api
        run: |
          output=$(curl --location 'http://localhost:3000' --data '<root><child>content</child></root>')
          expected_output='{"xml":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n<root><child>content</child></root>\n",';
          if echo "$output" | grep -q "Passthrough mode"; then
            exit 1
          fi
          echo "$output" | jq

      - name: Stop running containers
        run: |
          docker stop $(docker ps -q)

  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date --utc +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "commit_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-push
        with:
          push: true
          load: false
          platforms: linux/amd64,linux/arm64
          target: api
          tags: |
            ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api:latest
            ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api:${{ github.sha }}
            ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api:master-${{ steps.commit_sha.outputs.commit_sha }}-${{ steps.date.outputs.date }}
      - name: Generate artefact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api
          subject-digest: ${{ steps.build-push.outputs.digest }}
