name: Verify API
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  check-api-build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node dependencies
        run: yarn

      - name: Run jest tests
        run: yarn test

      - name: Run api in docker container
        run: |
          docker buildx build -t epp-biorxiv-xslt:api --target api .
          docker run -d -p 3000:80 epp-biorxiv-xslt:api
          sleep 5 # wait for the container to start up

      - name: Check api
        run: |
          curl --location 'http://localhost:3000' --data '<root><child>content</child></root>'
          docker stop $(docker ps -q) # stop running containers
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          GITHASH=$(git log -1 --pretty=format:"%H")
          GITSHORTHASH=$(git log -1 --pretty=format:"%H" | head -c 8)
          DATETIME=$(date -u '+%Y%m%d.%H%M')
          GITBRANCH=$(git branch --show-current)
          docker buildx build \
            -t ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api:latest \
            -t ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api:$GITHASH \
            -t ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api:$GITBRANCH-$GITSHORTHASH-$DATETIME \
            --platform linux/amd64,linux/arm64 --target api --push .
